import json
import re

# We will manually map the parsed table since the text is a bit messy and structured by newlines.
# From the text, we have substance classes and active ingredients.
# We will create a list of dictionaries.

data = [
    {"substance": "Prednison", "brand_names": ["Decortin"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein (> 20mg/d)", "therapy_pause_needed": "> 2 Monate", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Inebilizumab", "brand_names": ["Uplizna"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 6 Monate", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Obinutuzumab", "brand_names": ["Gazyvaro"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "Ja", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Ocrelizumab", "brand_names": ["Ocrevus"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "Ca. 18 Monate nach Therapieende", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Ofatumumab", "brand_names": ["Kesimpta", "Arzerra"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "Ca. 10 Monate nach Therapieende", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Rituximab", "brand_names": ["MabThera", "Rixathon", "Truxima"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 12 Monate", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Alemtuzumab", "brand_names": ["Lemtrada", "Campath"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 12 Monate", "immune_response_dead_vaccine": "Ausreichend"},
    {"substance": "Belimumab", "brand_names": ["Benlysta"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 3 Monate", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Adalimumab", "brand_names": ["Humira", "Amgevita", "Idacio"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 2 Monate", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Certolizumab", "brand_names": ["Cimzia"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 2 Monate", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Etanercept", "brand_names": ["Enbrel", "Benepali"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 2 Monate", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Golimumab", "brand_names": ["Simponi"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 3 Monate", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Infliximab", "brand_names": ["Remicade", "Inflectra", "Remsima"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 3 Monate", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Anifrolumab", "brand_names": ["Saphnelo"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "Keine Daten", "immune_response_dead_vaccine": "Keine Daten"},
    {"substance": "Anakinra", "brand_names": ["Kineret"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 1 Monat", "immune_response_dead_vaccine": "Ausreichend"},
    {"substance": "Canakinumab", "brand_names": ["Ilaris"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 3 Monate", "immune_response_dead_vaccine": "Ausreichend"},
    {"substance": "Basiliximab", "brand_names": ["Simulect"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "Keine Daten", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Dupilumab", "brand_names": ["Dupixent"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "Keine Daten", "immune_response_dead_vaccine": "Ausreichend"},
    {"substance": "Mepolizumab", "brand_names": ["Nucala"], "is_immunosuppressant": True, "live_vaccine_allowed": "Ja", "therapy_pause_needed": "Keine", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Benralizumab", "brand_names": ["Fasenra"], "is_immunosuppressant": True, "live_vaccine_allowed": "Ja", "therapy_pause_needed": "Keine", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Siltuximab", "brand_names": ["Sylvant"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 4 Monate", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Tocilizumab", "brand_names": ["RoActemra"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 2 Monate", "immune_response_dead_vaccine": "Ausreichend"},
    {"substance": "Sarilumab", "brand_names": ["Kevzara"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 2 Monate", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Satralizumab", "brand_names": ["Enspryng"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "Keine Daten", "immune_response_dead_vaccine": "Wohl ausreichend"},
    {"substance": "Ustekinumab", "brand_names": ["Stelara"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 15 Wochen", "immune_response_dead_vaccine": "Ausreichend"},
    {"substance": "Lebrikizumab", "brand_names": ["Ebglyss"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "Keine Daten", "immune_response_dead_vaccine": "Ausreichend"},
    {"substance": "Tralokinumab", "brand_names": ["Adtralza"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "Keine Daten", "immune_response_dead_vaccine": "Ausreichend"},
    {"substance": "Bimekizumab", "brand_names": ["Bimzelx"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "Keine Daten", "immune_response_dead_vaccine": "Ausreichend"},
    {"substance": "Brodalumab", "brand_names": ["Kyntheum"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "Keine Daten", "immune_response_dead_vaccine": "Ausreichend"},
    {"substance": "Ixekizumab", "brand_names": ["Taltz"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 3 Monate", "immune_response_dead_vaccine": "Ausreichend"},
    {"substance": "Secukinumab", "brand_names": ["Cosentyx"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 2 Monate", "immune_response_dead_vaccine": "Ausreichend"},
    {"substance": "Guselkumab", "brand_names": ["Tremfya"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 3 Monate", "immune_response_dead_vaccine": "Keine Daten"},
    {"substance": "Mirikizumab", "brand_names": ["Omvoh"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "Keine Daten", "immune_response_dead_vaccine": "Keine Daten"},
    {"substance": "Risankizumab", "brand_names": ["Skyrizi"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 21 Wochen", "immune_response_dead_vaccine": "Keine Daten"},
    {"substance": "Tildrakizumab", "brand_names": ["Ilumetri"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 17 Wochen", "immune_response_dead_vaccine": "Keine Daten"},
    {"substance": "Dimethylfumarat", "brand_names": ["Tecfidera", "Skilarence"], "is_immunosuppressant": True, "live_vaccine_allowed": "Eingeschränkt", "therapy_pause_needed": "Eingeschränkt", "immune_response_dead_vaccine": "Ausreichend"},
    {"substance": "Diroximelfumarat", "brand_names": ["Vumerity"], "is_immunosuppressant": True, "live_vaccine_allowed": "Eingeschränkt", "therapy_pause_needed": "Eingeschränkt", "immune_response_dead_vaccine": "Ausreichend"},
    {"substance": "Leflunomid", "brand_names": ["Arava"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 6 Monate", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Teriflunomid", "brand_names": ["Aubagio"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 6 Monate", "immune_response_dead_vaccine": "Ausreichend"},
    {"substance": "Etrasimod", "brand_names": ["Velsipity"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "2 Wochen", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Fingolimod", "brand_names": ["Gilenya"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 2 Monate", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Ozanimod", "brand_names": ["Zeposia"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 3 Monate", "immune_response_dead_vaccine": "Ausreichend"},
    {"substance": "Siponimod", "brand_names": ["Mayzent"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 1 Monat", "immune_response_dead_vaccine": "Ausreichend"},
    {"substance": "Glatirameracetat", "brand_names": ["Copaxone", "Clift"], "is_immunosuppressant": True, "live_vaccine_allowed": "Eingeschränkt", "therapy_pause_needed": "Eingeschränkt", "immune_response_dead_vaccine": "Ausreichend"},
    {"substance": "Interferon beta", "brand_names": ["Avonex", "Rebif", "Betaferon"], "is_immunosuppressant": True, "live_vaccine_allowed": "Ja", "therapy_pause_needed": "Keine", "immune_response_dead_vaccine": "Ausreichend"},
    {"substance": "Peginterferon alfa-2a", "brand_names": ["Pegasys"], "is_immunosuppressant": True, "live_vaccine_allowed": "Ja", "therapy_pause_needed": "Keine", "immune_response_dead_vaccine": "Ausreichend"},
    {"substance": "Sulfasalazin", "brand_names": ["Azulfidine", "Pleozone"], "is_immunosuppressant": True, "live_vaccine_allowed": "Ja", "therapy_pause_needed": "Keine", "immune_response_dead_vaccine": "Ausreichend"},
    {"substance": "Mesalazin", "brand_names": ["Salofalk", "Pentasa", "Claversal"], "is_immunosuppressant": True, "live_vaccine_allowed": "Ja", "therapy_pause_needed": "Keine", "immune_response_dead_vaccine": "Ausreichend"},
    {"substance": "Mifamurtid", "brand_names": ["Mepact"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "Keine Daten", "immune_response_dead_vaccine": "Keine Daten"},
    {"substance": "Omalizumab", "brand_names": ["Xolair"], "is_immunosuppressant": True, "live_vaccine_allowed": "Ja", "therapy_pause_needed": "Keine", "immune_response_dead_vaccine": "Keine Daten"},
    {"substance": "Nipocalimab", "brand_names": [], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 2 Wochen", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Rozanolixizumab", "brand_names": ["Rystiggo"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "Keine Daten", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Cyclophosphamid", "brand_names": ["Endoxan"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 3 Monate", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Dacarbazin", "brand_names": ["Detimedac"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "Keine Daten", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Ifosfamid", "brand_names": ["Holoxan"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "Keine Daten", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Trofosfamid", "brand_names": ["Ixoten"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "Keine Daten", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Mitoxantron", "brand_names": ["Novantron"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 3 Monate", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Cladribin", "brand_names": ["Mavenclad", "Leustatin"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 1 Monat", "immune_response_dead_vaccine": "Ausreichend bis Vermindert"},
    {"substance": "Irinotecan", "brand_names": ["Campto"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "Keine Daten", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Azathioprin", "brand_names": ["Imurek", "Azafalk"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 3 Monate", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Belatacept", "brand_names": ["Nulojix"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 3 Monate", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Ciclosporin", "brand_names": ["Sandimmun", "Deximune"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 1 Monat", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Voclosporin", "brand_names": ["Lupkynis"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 2 Monate", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "6-Mercaptopurin", "brand_names": ["Puri-Nethol"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "Keine Daten", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Tacrolimus", "brand_names": ["Prograf", "Advagraf", "Protopic"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 3 Monate", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Everolimus", "brand_names": ["Certican", "Afinitor"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 1 Monat", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Mycophenolat-Mofetil", "brand_names": ["CellCept"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 2 Monate", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Mycophenolsäure", "brand_names": ["Myfortic"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "Keine Daten", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Methotrexat", "brand_names": ["Lantarel", "Metex", "Metoject"], "is_immunosuppressant": True, "live_vaccine_allowed": "Eingeschränkt (Niedrigdosis) / Nein (Hochdosis)", "therapy_pause_needed": "> 1 Monat (Niedrigdosis) / > 2 Monate (Hochdosis)", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Abatacept", "brand_names": ["Orencia"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 1 Monat", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Natalizumab", "brand_names": ["Tysabri"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 3 Monate", "immune_response_dead_vaccine": "Ausreichend"},
    {"substance": "Vedolizumab", "brand_names": ["Entyvio"], "is_immunosuppressant": True, "live_vaccine_allowed": "Eingeschränkt", "therapy_pause_needed": "Keine", "immune_response_dead_vaccine": "Ausreichend"},
    {"substance": "Baricitinib", "brand_names": ["Olumiant"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 1 Monat", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Filgotinib", "brand_names": ["Jyseleca"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 1 Monat", "immune_response_dead_vaccine": "Keine Daten"},
    {"substance": "Ritlecitinib", "brand_names": ["Litfulo"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "Keine Daten", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Tofacitinib", "brand_names": ["Xeljanz"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 2 Monate", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Upadacitinib", "brand_names": ["Rinvoq"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "Ja", "immune_response_dead_vaccine": "Vermindert"},
    {"substance": "Deucravacitinib", "brand_names": ["Sotyktu"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "> 1 Monat", "immune_response_dead_vaccine": "Keine Daten"},
    {"substance": "Apremilast", "brand_names": ["Otezla"], "is_immunosuppressant": True, "live_vaccine_allowed": "Ja", "therapy_pause_needed": "Keine", "immune_response_dead_vaccine": "Ausreichend"},
    {"substance": "Eculizumab", "brand_names": ["Soliris"], "is_immunosuppressant": True, "live_vaccine_allowed": "Ja", "therapy_pause_needed": "Keine", "immune_response_dead_vaccine": "Ausreichend"},
    {"substance": "Crovalimab", "brand_names": [], "is_immunosuppressant": True, "live_vaccine_allowed": "Ja", "therapy_pause_needed": "Keine", "immune_response_dead_vaccine": "Ausreichend"},
    {"substance": "Ravulizumab", "brand_names": ["Ultomiris"], "is_immunosuppressant": True, "live_vaccine_allowed": "Ja", "therapy_pause_needed": "Keine", "immune_response_dead_vaccine": "Ausreichend"},
    {"substance": "Zilucoplan", "brand_names": ["Zilbrysq"], "is_immunosuppressant": True, "live_vaccine_allowed": "Ja", "therapy_pause_needed": "Keine", "immune_response_dead_vaccine": "Keine Daten"},
    {"substance": "Avacopan", "brand_names": ["Tavneos"], "is_immunosuppressant": True, "live_vaccine_allowed": "Keine Daten", "therapy_pause_needed": "Keine Daten", "immune_response_dead_vaccine": "Keine Daten"},
    {"substance": "Pegcetacoplan", "brand_names": ["Aspaveli", "Syfovre"], "is_immunosuppressant": True, "live_vaccine_allowed": "Ja", "therapy_pause_needed": "Keine", "immune_response_dead_vaccine": "Ausreichend"},
    {"substance": "Sutimlimab", "brand_names": ["Enjaymo"], "is_immunosuppressant": True, "live_vaccine_allowed": "Ja", "therapy_pause_needed": "Keine", "immune_response_dead_vaccine": "Ausreichend"},
    {"substance": "Iptacopan", "brand_names": ["Fabhalta"], "is_immunosuppressant": True, "live_vaccine_allowed": "Ja", "therapy_pause_needed": "Keine", "immune_response_dead_vaccine": "Ausreichend"},
    {"substance": "Danicopan", "brand_names": ["Voydeya"], "is_immunosuppressant": True, "live_vaccine_allowed": "Ja", "therapy_pause_needed": "Keine", "immune_response_dead_vaccine": "Keine Daten"},
    {"substance": "Pirfenidon", "brand_names": ["Esbriet"], "is_immunosuppressant": True, "live_vaccine_allowed": "Keine Daten", "therapy_pause_needed": "Keine Daten", "immune_response_dead_vaccine": "Keine Daten"},
    {"substance": "Efgartigimod alfa", "brand_names": ["Vyvgart"], "is_immunosuppressant": True, "live_vaccine_allowed": "Nein", "therapy_pause_needed": "Keine Daten", "immune_response_dead_vaccine": "Ausreichend"},
    
    # Common Travel / Non-immunosuppressant drugs example for completeness of the "foundation"
    {"substance": "Atovaquon, Proguanil", "brand_names": ["Malarone", "Atovaquon/Proguanil", "Malarone Junior"], "is_immunosuppressant": False, "live_vaccine_allowed": "Ja", "therapy_pause_needed": "Keine", "immune_response_dead_vaccine": "Ausreichend"},
    {"substance": "Ibuprofen", "brand_names": ["Ibuprofen", "Dolormin", "Nurofen"], "is_immunosuppressant": False, "live_vaccine_allowed": "Ja", "therapy_pause_needed": "Keine", "immune_response_dead_vaccine": "Ausreichend"},
    {"substance": "Paracetamol", "brand_names": ["Paracetamol", "Ben-u-ron", "Thomapyrin"], "is_immunosuppressant": False, "live_vaccine_allowed": "Ja", "therapy_pause_needed": "Keine", "immune_response_dead_vaccine": "Ausreichend"},
    {"substance": "Mefloquin", "brand_names": ["Lariam"], "is_immunosuppressant": False, "live_vaccine_allowed": "Ja", "therapy_pause_needed": "Keine", "immune_response_dead_vaccine": "Ausreichend"},
    {"substance": "Doxycyclin", "brand_names": ["Doxycyclin", "Vibramycin"], "is_immunosuppressant": False, "live_vaccine_allowed": "Ja", "therapy_pause_needed": "Keine", "immune_response_dead_vaccine": "Ausreichend"},
    {"substance": "Artemether, Lumefantrin", "brand_names": ["Riamet"], "is_immunosuppressant": False, "live_vaccine_allowed": "Ja", "therapy_pause_needed": "Keine", "immune_response_dead_vaccine": "Ausreichend"},
]

with open('drugs_germany.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("Saved drugs_germany.json successfully.")
